%cbmag022020
%finds the largest absolute value of the displacement of the Guyot Hall seismometer, 
%generated by the campus blasts in the x, y, and z directions
%Campus Blasts: 2-18-2020 and 2-21-2020

%last edited March 19, 2020 by Yuri Tamama


%set file names (from mcms2mat.m) and time step
feb18file = "PP.S0001.00.HHA_MC-PH1_0248_20200218_160000.mat";
feb21file = "PP.S0001.00.HHA_MC-PH1_0248_20200221_160000.mat";

%choose which campus blast to analyze
%set to 1 if choosing; 0 if not choosing
feb18 = 1;
feb21 = 0;

%error catching
if (feb18 == 1) && (feb21 == 1)
    error("Can't analyze both at once!")
end
if (feb18 == 0) && (feb21 == 0)
    error("Analyze one campus blast!")
end


%different pathways based on which file to load
%February 18 blast
if feb18 == 1
    %load .mat data
    load(feb18file);     

    %crop displacement vectors to blast times 
    %in seconds from 16:00:00 - 17:00:00 GMT
    firstind = (1804.5*100) + 1;   
    lastind = (1807.5*100) + 1;
    

%February 21 blast
else
    %load .mat data
    load(feb21file);     

    %crop displacement vectors to blast times
    %in seconds from 16:00:00 - 17:00:00 GMT
    firstind = (2563.5*100) + 1;   
    lastind = (2567*100) + 1;
    
end


%crop displacement vectors to blast times
sx = sx(firstind:lastind);
sy = sy(firstind:lastind);
sz = sz(firstind:lastind);

%find maximum absolute value of displacement (nm)
magx = max(abs(sx));
magy = max(abs(sy));
magz = max(abs(sz));







