# GuyotSeismology Examples

These MATLAB scripts contain examples on how to use the functions in this repository. The datafiles folder contains (or will contain!) data necessary for some functions. The figures folder contains figures that will be generated by these functions. 