% sampleeqvis.m

% Example on creating a plot of which earthquakes can be "seen" by the
% Nanometrics seismometer in Guyot Hall.

% Before running this code, you will have generated a bunch of seismograms,
% corresponding to the times when the seismic waves generated by
% earthquakes would have reached Guyot Hall. Then, you can decide whether 
% you see the earthquake in the seismogram, and keep track of the 
% "visibility" of each one in a file formatted similarly to 
% visibleearthquakes_0.010.021020.csv

% Directories to get data and save the figures
datadir=fullfile(pwd,'datafiles');
savedir=fullfile(pwd,'figures');

csvfile='visibleearthquakes_0.010.021020.csv';
csvfile=fullfile(datadir,csvfile);
% The earthquakes were plotted in displacement
measval=0;
% Signals filtered from 0.02 to 10 Hz
frequency=[0.01 0.02 10.0 20.0];
magrange=[5.5 10];
% No custom title or figure name
customtitle='';
customfigname='';
% Categorize earthquakes as "shallow," "intermediate," or "deep"
cmaptype=2;
saveplot=1;
%
figurehdl=visibleeq(csvfile,measval,frequency,magrange,cmaptype,...
  saveplot,savedir,customtitle,customfigname);


